### ISSUE TITLE
Mejora

### ISSUE THREAD

**Issue by damian-miquel** [iesgrancapitan-entornos/practica-5-github-issues-Cristinaprja#1]
Sería mejor si hicieras el import alprincipio del programa.
https://github.com/iesgrancapitan-entornos/practica-5-github-issues-Cristinaprja/blob/298a75ce2b2ae310bf222b7fc092683d0b076deb/Circulo.java#L13

**Comment by Cristinaprja** [comment]
Vale, lo cambio, gracias

**Comment by jaimerabasco** [comment]
Solo cierras 1 issue, en lugar de los 4 que pide la práctica @Cristinaprja
